// Copyright 2026 Alessandro Masat
// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file math.h
 * @brief `aether::math` — device-legal scalar math dispatch.
 *
 * A facade over a small set of scalar math primitives usable identically
 * from host and device code: `abs`, `floor`, `%fma`, `fmax`, `fmin`, `min`,
 * `pow`, `%sqrt`, plus `isfinite` (supersedes a local shim previously used
 * in `aether/expr/Reduce.h`) and the `sin`/`cos`/`sincos` trio backed on
 * the device by `detail/BoundedTrig.h`.
 *
 * Device compiles route every entry point to the CUDA math intrinsic
 * (`fabsf`/`::%fabs`, ...) — for `sin`/`cos`/`sincos` on `double`, that
 * route is `detail::cwSin`/`cwCos`/`cwSinCos` (total over all doubles, no
 * stack usage, no call), not libdevice's `__nv_sin`/`__nv_cos`. Host compiles
 * route to `std::`. No `std::` call ever appears on the device path.
 *
 * THE FULL SET (with the headers included at the end of this file):
 * `abs`, `sign`, `copysign`, `clip`, `isnan`, `isinf`, `isfinite`, `fma`,
 * `fmax`, `fmin`, `min`, `pow`, `sqrt` (here); `exp`, `exp2`, `exp10`,
 * `expm1`, `log`, `log2`, `log10`, `log1p` (`explog.h`); `rsqrt`, `cbrt`,
 * `hypot` (`root.h`); `sin`, `cos`, `sincos` (here), `tan`, `tanh`
 * (`trig.h`); `sinh`, `cosh`, `asinh`, `acosh`, `atanh` (`hyperbolic.h`);
 * `asin`, `acos`, `atan`, `atan2` (`invtrig.h`); `floor` (here), `ceil`,
 * `trunc`, `round` (half away from zero), `rint` (half to even), `fmod`
 * (sign of the dividend), `remainder` (numpy's: sign of the divisor),
 * `fdim` (`round.h`); `erf`, `erfc` (`special.h`). Not provided yet:
 * `lgamma`/`tgamma`/`digamma`, Bessel functions.
 *
 * `sign(NaN)` is `0` here (numpy's `sign` returns NaN): see `sign`.
 *
 * SUPPORTED TYPES. `float`/`double` everywhere. The five certified banded
 * entry points — `abs`, `copysign`, `fmax`/`min`/`fmin`, `pow` — also
 * accept `aether::banded::{Band, BandedReal}` and return the working
 * carrier `Band`, so a banded chain stays unpacked through them. They are
 * generated by the constrained `AETHER_MATH_*_BAND` companions rather than
 * by a branch inside the scaffold; see `detail/MathDispatch.h` for why the
 * binary scaffold's own requires-clause had to be edited for that to work
 * at all, and `detail/BandedFwd.h` for how the companions see the banded
 * family without dragging its definitions into every TU that computes
 * `sin(double)`. `pow`'s banded body is `pow = exp(b*log(a))`
 * (`aether/banded/BandExpLog.h`); `explog.h` (below) widens `exp`/`log`
 * themselves to the same banded entry-point set. Every other `aether::math`
 * name on a banded operand is still a hard compile error — the honest
 * answer for what has not yet been ported.
 *
 * OPT-IN HOST VECTOR MATH. Defining `AETHER_HOST_VECTOR_MATH` in a GCC
 * x86-64 host TU routes the `double` host legs of exp/exp2/exp10/expm1/
 * log/log2/log10/log1p/pow/sin/cos/sincos/tan/tanh/sinh/cosh/asinh/acosh/
 * atanh/atan/atan2/asin/acos/sqrt/rsqrt/cbrt/hypot/floor/ceil/trunc/round/
 * rint/fdim to vector-ABI functions the auto-vectoriser can call, `abs`/
 * `copysign` to inline sign-bit masks, and `fmax`/`fmin`/`min` to
 * branch-free inline selects the
 * vectoriser handles natively (`detail/HostVectorMath.h`; identical to
 * `std::` up to the sign of a +0/-0 tie, which C leaves unspecified);
 * results of the
 * transcendental ones are then within the ULP
 * bounds listed in `aether/backend/cpu/simd/math/PacketMath.h` instead of
 * glibc's. Without the macro nothing changes.
 *
 * `aether/math/explog.h` adds `exp`/`exp2`/`exp10`/`log`/`log2`/`log10`
 * (included below), and `sign` (hand-written like `%fma`/`isfinite` below
 * it: `sign(0) == 0` for either IEEE zero sign, and for NaN, since neither
 * compares `>` nor `<` zero).
 */

#include <cmath>
#include <type_traits>

#include "aether/macros.h"
#include "aether/math/detail/BoundedTrig.h"
#include "aether/math/detail/MathDispatch.h"

namespace aether {
namespace math {

/** @brief Absolute value. */
AETHER_MATH_UNARY(abs, fabsf, ::fabs, AETHER_MATH_HOST_ROUTE(abs, x))
/** @brief …on a banded operand: three XORs against the leading limb's own sign
 *         bit, exact and total, returning the working carrier. */
AETHER_MATH_UNARY_BAND(abs, abs)

/** @brief `|a|` with the sign of `b`. `copysign` is one of the five certified
 *         banded entry points, and a facade entry that exists for the
 *         emulated scalar but not for `double` would be a mode-divergence
 *         trap of exactly the kind this facade exists to prevent. */
AETHER_MATH_BINARY(copysign, copysignf, ::copysign, AETHER_MATH_HOST_ROUTE(copysign, a, b))
/** @brief …on a banded operand: ONE XOR of two sign bits, then the mask. */
AETHER_MATH_BINARY_BAND(copysign, copysign)

/** @brief Floor. */
AETHER_MATH_UNARY(floor, floorf, ::floor, AETHER_MATH_HOST_ROUTE(floor, x))

/** @brief Maximum of two values (floating-point `fmax` semantics — a NaN
 *         operand is ignored when the other is not NaN). */
AETHER_MATH_BINARY(fmax, fmaxf, ::fmax, AETHER_MATH_HOST_ROUTE(fmax, a, b))
/** @brief …on a banded operand. The comparison is the certified `sub`'s leading
 *         limb, never a lexicographic limb compare (which is WRONG — see
 *         `banded::detail::fmax`'s own counterexample). */
AETHER_MATH_BINARY_BAND(fmax, fmax)

/** @brief Minimum of two values (floating-point `fmin` semantics). */
AETHER_MATH_BINARY(fmin, fminf, ::fmin, AETHER_MATH_HOST_ROUTE(fmin, a, b))
/** @brief …on a banded operand. @see fmax. */
AETHER_MATH_BINARY_BAND(fmin, fmin)

/** @brief Minimum of two values — alias entry point
 *         alongside `fmax`/`fmin`; same dispatch as `fmin`. */
AETHER_MATH_BINARY(min, fminf, ::fmin, AETHER_MATH_HOST_ROUTE(fmin, a, b))
/** @brief …on a banded operand — the same certified `fmin`, under the alias
 *         spelling, so a consumer migrating by spelling swap keeps both names. */
AETHER_MATH_BINARY_BAND(min, fmin)

/** @brief `a` raised to the power `b`. */
AETHER_MATH_BINARY(pow, powf, ::pow, AETHER_MATH_HOST_ROUTE(pow, a, b))
/** @brief …on a banded operand: `pow = exp(b*log(a))` over `BandExpLog.h`'s
 *         ported `exp`/`log`, certified over `banded::detail::bandPowAdmits`.
 *         @see `banded::detail::BandedFacade::pow`. */
AETHER_MATH_BINARY_BAND(pow, pow)

/** @brief Square root. */
AETHER_MATH_UNARY(sqrt, sqrtf, ::sqrt, AETHER_MATH_HOST_ROUTE(sqrt, x))

/// \cond AETHER_DOXYGEN_REQUIRES_OWN_LINE_WORKAROUND
template<class T>
    requires(!aether::banded::IsBandedFamily<T>)
AETHER_DEVICEHOST() AETHER_FORCEINLINE() T fma(T a, T b, T c)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::fma: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    if constexpr (std::is_same_v<T, float>) {
        return fmaf(a, b, c);
    } else {
        return ::fma(a, b, c);
    }
#else
    return std::fma(a, b, c);
#endif
}
/// \endcond

/**
 * @brief Sign of `x`: `+1` for `x > 0`, `-1` for `x < 0`, `0` otherwise
 *        (`x == +0`, `x == -0`, or NaN — a NaN compares `false` to both
 *        `>` and `<` zero, so it falls through to `0` the same way IEEE
 *        zero does; documented rather than special-cased). No device/host
 *        split needed — pure comparison against `T{0}`, identical on both
 *        routes (unlike `%fma`/`isfinite` above, which route to different
 *        device/host intrinsics).
 */
template<class T>
AETHER_DEVICEHOST() AETHER_FORCEINLINE() T sign(T x)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::sign: T must be float or double");
    if (x > T{ 0 }) {
        return T{ 1 };
    } else if (x < T{ 0 }) {
        return T{ -1 };
    } else {
        return T{ 0 };
    }
}

/**
 * @brief Whether `x` is finite (not Inf, not NaN). Supersedes
 *        `aether/expr/Reduce.h`'s local `detail::isfinite_` shim with the
 *        real dispatch header.
 */
template<class T>
AETHER_DEVICEHOST() AETHER_FORCEINLINE() bool isfinite(T x)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::isfinite: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    return ::isfinite(x);
#else
    return std::isfinite(x);
#endif
}

/** @brief Whether `x` is NaN. */
template<class T>
AETHER_DEVICEHOST() AETHER_FORCEINLINE() bool isnan(T x)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::isnan: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    return ::isnan(x);
#else
    return std::isnan(x);
#endif
}

/** @brief Whether `x` is `+inf` or `-inf`. */
template<class T>
AETHER_DEVICEHOST() AETHER_FORCEINLINE() bool isinf(T x)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::isinf: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    return ::isinf(x);
#else
    return std::isinf(x);
#endif
}

/**
 * @brief `x` limited to `[lo, hi]`, with numpy's `clip` semantics:
 *        `minimum(maximum(x, lo), hi)` where `maximum`/`minimum` propagate
 *        NaN (unlike `fmax`/`fmin`), so a NaN in any argument gives NaN, and
 *        `lo > hi` gives `hi`. Pure compares, identical on host and device.
 */
template<class T>
AETHER_DEVICEHOST() AETHER_FORCEINLINE() T clip(T x, T lo, T hi)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::clip: T must be float or double");
    const T t = (x >= lo || x != x) ? x : lo;
    return (t <= hi || t != t) ? t : hi;
}

/**
 * @brief Sine of `x`. Device FP64 path routes to `detail::cwSin` (Cody-
 *        Waite below 2^31, full-range Payne-Hanek above, NaN for Inf/NaN,
 *        STACK=0 — see `detail/BoundedTrig.h`); device FP32 routes to the native
 *        `sinf`; host routes to `std::sin`.
 */
template<class T>
AETHER_MATH_HOST_ABI AETHER_DEVICEHOST() AETHER_FORCEINLINE() T sin(T x)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::sin: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    if constexpr (std::is_same_v<T, float>) {
        return sinf(x);
    } else {
        return detail::cwSin(x);
    }
#else
    return AETHER_MATH_HOST_ROUTE(sin, x);
#endif
}

/**
 * @brief Cosine of `x`. Device FP64 path routes to `detail::cwCos`; device
 *        FP32 routes to the native `cosf`; host routes to `std::cos`.
 */
template<class T>
AETHER_MATH_HOST_ABI AETHER_DEVICEHOST() AETHER_FORCEINLINE() T cos(T x)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::cos: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    if constexpr (std::is_same_v<T, float>) {
        return cosf(x);
    } else {
        return detail::cwCos(x);
    }
#else
    return AETHER_MATH_HOST_ROUTE(cos, x);
#endif
}

/**
 * @brief Sine and cosine of `x`, sharing the argument reduction. Device
 *        FP64 path routes to `detail::cwSinCos`; device FP32 routes to the
 *        native `sincosf`; host computes `std::sin`/`std::cos` separately.
 */
template<class T>
AETHER_MATH_HOST_ABI AETHER_DEVICEHOST() AETHER_FORCEINLINE() void sincos(T x, T* sinOut, T* cosOut)
{
    static_assert(std::is_same_v<T, float> || std::is_same_v<T, double>, "aether::math::sincos: T must be float or double");
#if defined(AETHER_DEVICE_COMPILE)
    if constexpr (std::is_same_v<T, float>) {
        sincosf(x, sinOut, cosOut);
    } else {
        detail::cwSinCos(x, *sinOut, *cosOut);
    }
#else
    *sinOut = AETHER_MATH_HOST_ROUTE(sin, x);
    *cosOut = AETHER_MATH_HOST_ROUTE(cos, x);
#endif
}

} // namespace math
} // namespace aether

#include "aether/math/detail/MathDispatchUndef.h"

// Included AFTER this file's own MathDispatchUndef.h pass (never before
// it): explog.h runs its OWN independent MathDispatch.h
// include/define/AETHER_MATH_UNARY-invoke/undef cycle, self-contained
// exactly like this file's — interleaving it BEFORE this file's own
// AETHER_MATH_UNARY/BINARY invocations above would undef those macros out
// from under abs/floor/fmax/fmin/min/pow/sqrt (confirmed by a real build
// failure during authoring: "'fmin' is not a member of 'aether::math'" at
// every consumer, not even inside explog.h itself — the macros are shared,
// paired #include state, not a scoped one).
#include "aether/math/explog.h"

// Included AFTER explog.h's own MathDispatchUndef.h pass, same reason
// explog.h itself is ordered after this file's: root.h runs its OWN
// independent MathDispatch.h include/define/invoke/undef cycle.
#include "aether/math/root.h"

// Included AFTER root.h's own MathDispatchUndef.h pass, same reason
// explog.h/root.h are each ordered after the file before them: trig.h runs
// its OWN independent MathDispatch.h include/define/invoke/undef cycle.
#include "aether/math/trig.h"
// Included AFTER root.h's own MathDispatchUndef.h pass, same reason:
// round.h runs its OWN independent MathDispatch.h include/define/invoke/undef
// cycle.
#include "aether/math/round.h"
// Included AFTER root.h's own MathDispatchUndef.h pass, same reason:
// invtrig.h runs its OWN independent MathDispatch.h include/define/invoke/undef
// cycle.
#include "aether/math/invtrig.h"
// Same reason: each of these runs its own MathDispatch.h cycle.
#include "aether/math/hyperbolic.h"
#include "aether/math/special.h"
