// Copyright 2026 Alessandro Masat
// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file BandInvTrig.h
 * @brief `atan` / `atan2` / `asin` / `acos` over `Band`, with explicit
 *        `fma` and no `std::` math in device code.
 *
 * @section builds_on Builds on `AtanSector.h`
 * `atan2`/`atan`'s reduction consumes `aether::banded::detail::AtanSector`/
 * `atanSector` (`AtanSector.h`) unchanged. The matched-pair invariant that
 * table carries -- `{t = tan(phi_i) as stored, phi_i = atan(t) computed
 * from that stored t}`, derivation order load-bearing -- is preserved by
 * construction: this file only consumes `atanSector(b, a)`'s returned
 * `{t, phi}` pair inside `atan2`'s reduction, and never recomputes or
 * regenerates the table.
 *
 * @section fmaRawFromExpLog Reuses `BandExpLog.h`'s fma helpers
 * `asinCoreRaw`/`atanCoreRaw`'s Horner ladders consume `fmaRawNoCancel`/
 * `fmaRawSNoCancel`/`ddFma` (unnormalized-fma and double-float Horner
 * step) from `BandExpLog.h` rather than a second copy of the same
 * helpers.
 *
 * @section piO2Gap `bandPiO2()`
 * `asin`/`acos`/`atan2`'s reconstruction all consume `bandPiO2()` (`B` in
 * `{0, pi/2, pi}`, see each function's own doc comment below) -- the same
 * three Cody-Waite limbs `sin`/`cos`/`trigReduce` reduce against, so the
 * forward and inverse families stay on the same circle. Only the first
 * three limbs are needed here; CW4 and the `2/pi` reduction constants
 * belong to `trigReduce`'s own Payne-Hanek-style argument reduction, which
 * this file's ops do not perform. The limbs and `bandPiO2()` itself live
 * in `aether/banded/detail/PiConstants.h`, shared with `BandTrig.h`.
 *
 * @section bandDivisorAdmitsGap `bandDivisorAdmits`
 * `bandAtan2Admits` calls `bandDivisorAdmits`, a generic admission
 * predicate for a division's divisor (ceiling and floor legs, both
 * polarities). It has no home in `Band.h`, so it is defined in this file.
 *
 * @section matchedpair The matched-pair invariant
 * `atan2`'s reduction rotates by `sec.t` (a stored `Band` value) and adds
 * back `sec.phi` (`atan` of that same stored `sec.t`, not of the nominal
 * angle it was cut from) -- `fmaRaw(neg(a), sec.t, b)` / `fmaRaw(b, sec.t,
 * a)` for the rotated ratio, `add(sec.phi, s)` for the reconstruction. If
 * the table were ever regenerated by deriving `t` from `phi` instead (the
 * wrong order), the reduction would still compile and return a finite
 * answer -- just a silently wrong one, because the identity `atan(q) =
 * phi + atan((q-T)/(1+qT))` only holds exactly for `phi = atan(T)`, not
 * for an independently-rounded `T` derived from an independently-rounded
 * `phi`. This file never touches or re-derives the table (@see
 * `tests/bandmath/BandMathCertInvTrig.h`, which perturbs a standalone
 * copy by one float ULP on `t.hi` alone to demonstrate the invariant is
 * load-bearing).
 *
 * @section asinbranches asin's two branches
 * `asinReducedRaw`'s `high`/`low` branches diverge in a warp (a mixed
 * warp pays the sum of both), so they are kept as one function with an
 * internal branch rather than split into two public entry points; the two
 * branches' SASS/cert rows stay separate in this file's own test files.
 *
 * A second, host/device consequence of the same branch split:
 * `asinReducedRaw`'s high branch (`|x| > 0.5`) calls `RsqrtCore.h::sqrt_`,
 * whose seed diverges between host and device (hardware `rsqrt.approx.f32`
 * on device, `1.0f/sqrtf` on host -- @see `RsqrtCore.h`), so `asin`/`acos`
 * only match host and device to within tolerance on that branch. The low
 * branch (`|x| <= 0.5`, no `sqrt_` call) and all of `atan`/`atan2` (which
 * never call `sqrt_`) stay bit-identical between host and device.
 */

#include "aether/banded/Band.h"
#include "aether/banded/detail/PiConstants.h"
#include "aether/banded/AtanSector.h"
#include "aether/banded/BandExpLog.h" // fmaRaw/fmaRawNoCancel/fmaRawS/fmaRawSNoCancel/ddFma
#include "aether/banded/RsqrtCore.h"  // sqrt_ -- asin/acos's own HIGH branch
#include "aether/macros.h"

#include <cstdint>

namespace aether {
namespace banded {
namespace detail {

// =========================================================================
//  bandPiO2 -- see this file's own "piO2Gap" section above. The first
//  three Cody-Waite pi/2 limbs; already a valid normalized carrier
//  (|CW2| = 2^-24.45 <= ulp(CW1) = 2^-23, |CW3| = 2^-49.05 <= ulp(CW2)).
// =========================================================================
// pi/2 Cody-Waite limbs + bandPiO2(): aether/banded/detail/PiConstants.h


// =========================================================================
//  asinCoreRaw -- `asin(t)/t` as a polynomial in `u = t*t`, `|t| <= 1/2`.
//  `c_0 == 1` exactly -> the terminal step is a scalar-addend
//  `fmaRawSNoCancel`, which pins `asin(t) == t` bit-exactly wherever `u`
//  underflows. `NoCancel` is provable: every `c_j > 0` (positive Taylor
//  coefficients), so the Horner sum never loses a leading limb to
//  cancellation -- `exp`'s situation, not `sin`'s.
// =========================================================================
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() BandRaw asinCoreRaw(Band u)
{
    float p = 1.6816094285e-03f;                 // c30
    p       = fmaRN(u.hi, p, 1.7680810997e-03f);  // c29
    p       = fmaRN(u.hi, p, 1.8622264033e-03f);  // c28
    p       = fmaRN(u.hi, p, 1.9650335889e-03f);  // c27
    p       = fmaRN(u.hi, p, 2.0776609890e-03f);  // c26
    p       = fmaRN(u.hi, p, 2.2014740389e-03f);  // c25
    p       = fmaRN(u.hi, p, 2.3380918428e-03f);  // c24
    p       = fmaRN(u.hi, p, 2.4894487578e-03f);  // c23
    p       = fmaRN(u.hi, p, 2.6578705292e-03f);  // c22
    p       = fmaRN(u.hi, p, 2.8461783659e-03f);  // c21
    p       = fmaRN(u.hi, p, 3.0578216538e-03f);  // c20
    p       = fmaRN(u.hi, p, 3.2970595639e-03f);  // c19
    p       = fmaRN(u.hi, p, 3.5692052916e-03f);  // c18
    p       = fmaRN(u.hi, p, 3.8809645921e-03f);  // c17
    p       = fmaRN(u.hi, p, 4.2409072630e-03f);  // c16
    p       = fmaRN(u.hi, p, 4.6601435170e-03f);  // c15

    float ph = p, pl = 0.0f;
    ddFma(u.hi, u.lo, ph, pl, 5.1533095539e-03f, 1.2845828568e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 5.7400376536e-03f, 1.7246714473e-11f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 6.4472104423e-03f, -1.3038516100e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 7.3125259951e-03f, -1.2147685635e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 8.3903353661e-03f, 4.4348694161e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 9.7616091371e-03f, 3.9213582381e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 1.1551801115e-02f, -2.1913472426e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 1.3964843936e-02f, -1.8626451770e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 1.7352763563e-02f, 8.5968238084e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 2.2372158244e-02f, 8.4665691125e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 3.0381944031e-02f, 4.1392114736e-10f, ph, pl);

    BandRaw q{ ph, pl, 0.0f };
    q = fmaRawNoCancel(u, q, BandRaw{ 4.4642858207e-02f, -1.0643687043e-09f, 4.7580987242e-17f });
    q = fmaRawNoCancel(u, q, BandRaw{ 7.5000002980e-02f, -2.9802322832e-09f, 4.4408921647e-17f });
    q = fmaRawNoCancel(u, q, BandRaw{ 1.6666667163e-01f, -4.9670538793e-09f, 1.4802974103e-16f });
    return fmaRawSNoCancel(u, q, 1.0f); // c0 == 1 exactly -> scalar addend
}

// =========================================================================
//  atanCoreRaw -- `atan(t)/t` as a polynomial in `u = t*t`, `|t| <= tan(5 deg)`.
//  Coefficients alternate in sign; the `NoCancel` claim holds because the
//  retained fraction stays >= 0.9954 at every Band step.
// =========================================================================
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() BandRaw atanCoreRaw(Band u)
{
    float p = -5.2631579340e-02f;                 // c9
    p       = fmaRN(u.hi, p, 5.8823529631e-02f);   // c8
    p       = fmaRN(u.hi, p, -6.6666670144e-02f);  // c7
    p       = fmaRN(u.hi, p, 7.6923079789e-02f);   // c6
    p       = fmaRN(u.hi, p, -9.0909093618e-02f);  // c5

    float ph = p, pl = 0.0f;
    ddFma(u.hi, u.lo, ph, pl, 1.1111111194e-01f, -8.2784229471e-10f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, -1.4285714924e-01f, 6.3862120037e-09f, ph, pl);
    ddFma(u.hi, u.lo, ph, pl, 2.0000000298e-01f, -2.9802322832e-09f, ph, pl);

    BandRaw q{ ph, pl, 0.0f };
    q = fmaRawNoCancel(u, q, BandRaw{ -3.3333334327e-01f, 9.9341077586e-09f, -2.9605948206e-16f });
    return fmaRawSNoCancel(u, q, 1.0f); // c0 == 1 exactly -> scalar addend
}

/**
 * @brief The half `asin` and `acos` share: `asin(t)` on the reduced
 * argument. Returns `asin(t)` where `t` is `|x|` itself on `|x| <= 1/2`
 * and `sqrt_((1-|x|)/2)` above it, reporting which through `high` and
 * out-of-domain (`|x| > 1` or non-finite) through `bad` -- the caller owns
 * the NaN so `asin`/`acos` do not each need their own copy of the guard.
 *
 * @par The exact subtraction (the whole design of the high branch)
 * `1 - |x|` on `|x| in [1/2, 1]` is exact by Sterbenz; halving is an exact
 * limb-wise power-of-two scale. So `w = (1-|x|)/2` carries `|x|`'s full
 * relative accuracy however close to 1 it is, and the `1 - x^2`
 * cancellation a naive formulation would hit never happens.
 *
 * @par Host/device: the high branch is tolerance-level, not bit-exact
 * `t = sqrt_(w)` on this branch pulls in `RsqrtCore.h::sqrt_`'s own
 * host/device seed divergence -- @see this file's own header docstring,
 * "asin's two branches" section.
 */
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() Band asinReducedRaw(Band ax, bool& high, bool& bad)
{
    high = ax.hi > 0.5f;
    bad  = false;
    Band t, u;
    if (high) {
        const Band w = scalePow2f(sub(Band{ 1.0f, 0.0f, 0.0f }, ax), 0.5f);
        // `!(w.hi >= 0)` catches `|x| > 1` AND a non-finite argument in one
        // test: the domain edge is decided by the CARRIER, not the leading
        // limb alone.
        if (!(w.hi >= 0.0f)) {
            bad = true;
            return Band{ intAsFloat(0x7FC00000), 0.0f, 0.0f };
        }
        t = sqrt_(w);
        u = w;
    } else {
        t = ax;
        u = normalize(sqrRaw(ax));
    }
    return normalize(mulRaw(t, asinCoreRaw(u)));
}

/**
 * @brief `asin(x)` on the closed domain `[-1, 1]`.
 *
 * @par Domain -- hard, with no margin (`bandAsinAdmits`, below)
 * `[-1, 1]` is a mathematical limit, not a carrier one: `asin(1) == pi/2`
 * is a value real consumers evaluate at the domain's own endpoints, so a
 * declaration margin would reject those endpoints.
 *
 * @par Bound: 0.5 ULP-53, one leg, no absolute leg (see `kBandInvTrigRelBoundExp`)
 * Near `x = 0` the answer is `x * P(x^2)` with `P(0) = 1` exact, so the
 * relative error is the core's; near `x = +-1` the answer is `pi/2` minus a
 * term at most `pi/6`, so no leading bit is lost. There is nowhere for an
 * absolute floor to enter, unlike `sin`'s own reduction-injected one.
 *
 * @par Exact points
 * `asin(+-0) == +-0`, `asin(+-1) == +-pi/2` bit-exactly (`w` is `+0`,
 * `sqrt_(0)` is `+0`, `pi/2 - 0` returns `bandPiO2()` limb for limb), and
 * `asin(x) == x` bit-exactly for every `x` small enough that `x*x`
 * underflows FP32.
 */
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() Band asin(Band x)
{
    bool       high = false, bad = false;
    const Band v = asinReducedRaw(abs(x), high, bad);
    if (bad)
        return v; // already the NaN
    // asin|x| = high ? pi/2 - 2*asin(s) : asin(|x|)
    const Band m = high ? sub(bandPiO2(), scalePow2f(v, 2.0f)) : v;
    return (floatAsInt(x.hi) < 0) ? neg(m) : m;
}

/**
 * @brief `acos(x)` on the closed domain `[-1, 1]`.
 *
 * @par Three reconstructions, chosen by what each does NOT cancel
 *     x >  1/2   acos(x) = 2*asin(sqrt((1-x)/2))     -- NO subtraction, keeps relative accuracy near x=1
 *     |x| <= 1/2 acos(x) = pi/2 - asin(x)             -- subtracts at most pi/6 from at least pi/3
 *     x < -1/2   acos(x) = pi - 2*asin(sqrt((1+x)/2)) -- the positive branch's answer, reflected
 *
 * @par The negative branch is the positive one plus a reflection
 * `acos(-|x|) = pi - acos(|x|)`, applied to the magnitude's own answer --
 * ONE code path, not two; `1 + x` for `x` in `[-1,-1/2]` is the SAME
 * Sterbenz-exact `1 - |x|` subtraction `asinReducedRaw`'s high branch
 * already performs, in different clothing.
 *
 * @par Bound and exact points
 * `0.5` ULP-53, one leg, `asin`'s reasons. `acos(1) == +0`,
 * `acos(-1) == pi`, `acos(+-0) == pi/2` -- all exact; `acos(-0)` reaches
 * `pi/2` through `pi - pi/2`, exact because `pi` is `pi/2` scaled by a
 * power of two and the subtraction is limb-for-limb.
 */
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() Band acos(Band x)
{
    bool       high = false, bad = false;
    const Band v    = asinReducedRaw(abs(x), high, bad);
    if (bad)
        return v; // already the NaN
    const Band pio2 = bandPiO2();
    // acos|x| = high ? 2*asin(s) : pi/2 - asin(|x|)
    const Band m = high ? scalePow2f(v, 2.0f) : sub(pio2, v);
    return (floatAsInt(x.hi) < 0) ? sub(scalePow2f(pio2, 2.0f), m) : m;
}

/**
 * @brief `atan2(y, x)` -- the full plane, IEEE-754/C99 sign and zero
 * conventions. Bit-identical between host and device (no `sqrt_`/
 * hardware-seeded call anywhere in this body).
 *
 * @par Specials, in the order the standard states them
 *     either operand NaN                    -> NaN
 *     y = +-inf, x finite                   -> +-pi/2
 *     y = +-inf, x = +inf                   -> +-pi/4
 *     y = +-inf, x = -inf                   -> +-3pi/4
 *     y finite,  x = +inf                   -> +-0
 *     y finite,  x = -inf                   -> +-pi
 *     y = +-0,   x > 0 or x = +0            -> +-0
 *     y = +-0,   x < 0 or x = -0            -> +-pi
 *     y != 0,    x = +-0                    -> +-pi/2 by the sign of y
 * The sign of `y` is read from its leading limb's SIGN BIT, not a
 * comparison -- what makes the `+-0` rows differ from each other; `x = -0`
 * is likewise distinguished from `x = +0`. All sixteen sign/zero/finite
 * combinations are enumerated in this file's own test corpus, not sampled.
 *
 * @par The reduction: octant, sector (`AtanSector.h`), then one division
 * `b = min(|y|,|x|)`, `a = max`, `q = b/a` in `[0,1]`; `atanSector(b.hi,
 * a.hi)` picks one of five sectors and the identity `atan(q) = phi_i +
 * atan((q-T_i)/(1+q T_i))` (`T_i = tan(phi_i)`) moves the argument into
 * `[-tan(5 deg), tan(5 deg)]` -- formed from `b`/`a` BEFORE the division,
 * so the whole op still divides ONCE. Sector 0 is UNROTATED (`T=phi=0`),
 * not a special case: `fmaRaw`'s pair returns `b`/`a` exactly, so the head
 * arm's answer stays `t * P(t^2)` -- relative accuracy near zero, reached
 * with no branch.
 *
 * @par Reconstruction
 * `A = atan(b/a)` in `[0, pi/4]`; `atan2(|y|,|x|) = swap ? pi/2-A : A`
 * (`swap = |y|>|x|`), then `xNeg ? pi-that : that`, then negated if `y<0` —
 * folded into `B + sigma*A` with `B` in `{0,pi/2,pi}` (all exact limb-wise
 * scalings of `bandPiO2()`) and `sigma = (swap XOR xNeg) ? -1 : +1`.
 *
 * @par Bound
 * `0.5` ULP-53, one leg, everywhere (`kBandInvTrigRelBoundExp`).
 */
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() Band atan2(Band y, Band x)
{
    const Band  pio2 = bandPiO2();
    const int   kAbs = static_cast<int>(0x7FFFFFFFu);
    const float ayh  = intAsFloat(floatAsInt(y.hi) & kAbs);
    const float axh  = intAsFloat(floatAsInt(x.hi) & kAbs);
    const float kInf = intAsFloat(0x7F800000);
    const bool  yNeg = floatAsInt(y.hi) < 0; // the SIGN BIT: -0 counts
    const bool  xNeg = floatAsInt(x.hi) < 0;
    const Band  zeroB{ 0.0f, 0.0f, 0.0f };

    // Every special row delivers ONE of these four magnitudes, then takes
    // the sign of `y`. Collecting them keeps the table above readable.
    Band spec   = zeroB;
    bool isSpec = true;
    if (y.hi != y.hi || x.hi != x.hi)
        return Band{ intAsFloat(0x7FC00000), 0.0f, 0.0f };
    else if (ayh == kInf)
        spec = (axh == kInf) ? (xNeg ? add(pio2, scalePow2f(pio2, 0.5f))   // 3pi/4
                                     : scalePow2f(pio2, 0.5f))             // pi/4
                              : pio2;
    else if (axh == kInf || y.hi == 0.0f) // y == 0 BEFORE x == 0: atan2(+-0,+-0) is y's rule
        spec = xNeg ? scalePow2f(pio2, 2.0f) : zeroB;
    else if (x.hi == 0.0f)
        spec = pio2;
    else
        isSpec = false;
    if (isSpec)
        return yNeg ? neg(spec) : spec;

    const Band ay  = abs(y);
    const Band axb = abs(x);
    const bool swap = ayh > axh;
    const Band b    = swap ? axb : ay; // the smaller
    const Band a    = swap ? ay : axb; // the larger

    // The SECTOR rotation, applied to (b, a) so ONE division serves every
    // arm. No branch: sector 0 carries T = 0, so the fma pair returns b/a
    // exactly and the head arm costs the same two operations the rotated
    // ones do. `AtanSector.h`, do-not-touch -- @see this file's own
    // "matchedpair" section.
    const AtanSector sec = atanSector(b.hi, a.hi);
    const Band num = normalize(fmaRaw(neg(a), sec.t, b)); // b - a*tan(phi)
    const Band den = normalize(fmaRaw(b, sec.t, a));      // a + b*tan(phi)

    const Band t = div(num, den); // |t| <= tan(5 deg)
    const Band u = normalize(sqrRaw(t));
    const Band s = normalize(mulRaw(t, atanCoreRaw(u)));

    // A = atan(b/a) in [0, pi/4]. In a rotated sector s can be negative and
    // phi_i is at least 10 deg against |s| <= 5 deg -- one bit, never a
    // cancellation. In the head sector phi is zero and A IS s.
    const Band A = add(sec.phi, s);

    const Band B = scalePow2f(pio2, swap ? 1.0f : (xNeg ? 2.0f : 0.0f));
    const Band r = add(B, (swap != xNeg) ? neg(A) : A);
    return yNeg ? neg(r) : r;
}

/// @brief `atan(x)`: `atan2(x, 1)` exactly, the same body and bound,
/// deliberately not a second implementation. Bit-identical between host
/// and device, same reason `atan2` is.
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() Band atan(Band x)
{
    return atan2(x, Band{ 1.0f, 0.0f, 0.0f });
}

// =========================================================================
//  Admission predicates.
// =========================================================================

/// @brief Admission for a division's divisor (@see this file's own
/// "bandDivisorAdmitsGap" section for why it lives here, not in `Band.h`).
/// `a/b` materializes `recip(b)` at ~`2^-maxAbsExp(b)`; both legs are
/// needed (a huge divisor drives the reciprocal toward the carrier floor,
/// a tiny one drives it through the FP32 hard ceiling).
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() constexpr bool bandDivisorAdmits(
    int maxAbsExpDivisor, int minAbsExpDivisor, int margin = kBandAdmissionMargin)
{
    return bandIntermediateAdmits(-maxAbsExpDivisor, margin) && bandCeilingAdmits(-minAbsExpDivisor, margin);
}

/// @brief `|x|`'s domain edge for `asin`/`acos`: exactly `0` (`|x| <= 1`).
inline constexpr int kBandInvTrigMaxArgExp = 0;

/// @brief Admission for a consumer that calls `asin`/`acos`. ONE leg, NO
/// margin (a mathematical domain, not a carrier one -- @see `asin`'s own
/// doc comment above). Below the domain there is no floor leg: `asin`
/// returns its argument near zero, unconditionally.
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() constexpr bool bandAsinAdmits(int maxAbsExpArg)
{
    return maxAbsExpArg <= kBandInvTrigMaxArgExp;
}

/**
 * @brief Admission for a consumer that calls `atan2` (or `atan`). `atan2`
 * forms `a + b*tan(phi_i)` within one binade above the larger operand
 * (ceiling leg at `maxAbsExpArg + 1`), then divides by that sum
 * (`bandDivisorAdmits`'s own entry-shape rule). A bound stated only on the
 * quotient's relative conditioning misses two further failure modes this
 * predicate also has to reject:
 *
 * @par A third leg: the intermediates' own floor
 * `num`/`den` are `Band`-typed intermediates (`normalize(fmaRaw(...))`)
 * whose own absolute magnitude tracks the larger operand `a` (scaled by an
 * O(1) sector factor, `1 -+ T_i`), regardless of how well-conditioned the
 * final ratio is. `Band`'s carrier floor (`kBandCarrierFloorExp`) binds
 * every intermediate in a chain, not just the delivered value -- so when
 * both operands are simultaneously tiny (`maxAbsExpArg` deep negative,
 * e.g. `-107`), `num`'s own `lo`/`tail` limbs (at `hi`'s exponent minus
 * ~24/~48) fall through the FP32 hard subnormal floor before the division
 * even runs. Measured: `atan2(y,x)` with `y=x=2^-107` (sector 4, the
 * worst-case reduced argument `t = tan(5 deg)`) reads ~132 ULP off `pi/4`
 * -- verified against the identity `atan(T) + atan((1-T)/(1+T)) ==
 * atan(1)` at 50-digit precision (`T`/`phi` themselves confirmed accurate
 * to `2^-75`) -- the error is entirely in `num`/`den`'s own precision
 * loss, not in the matched-pair table.
 *
 * The fix: an explicit third leg, `bandIntermediateAdmits(maxAbsExpArg,
 * margin)`, binding the larger operand's own exponent to the same carrier
 * floor every other op's intermediates respect.
 *
 * @par A fourth leg: the reduced argument `t`'s own output floor
 * The quotient's relative conditioning (`|t| <= tan(5 deg)` always,
 * whatever the operand spread) is not the same claim as its absolute
 * magnitude carrying full carrier precision. `t`'s worst-case exponent is
 * `minAbsExpArg - maxAbsExpArg` (smaller operand at its declared floor,
 * larger at its declared ceiling); once `t.hi` itself drops into FP32
 * subnormal territory, `div()`'s own correction limbs (`lo` at
 * `~t.hi's exponent - 24`, `tail` at `~ - 48`) underflow through the FP32
 * hard floor and come back exactly zero -- `t` silently degrades from a
 * three-limb carrier to a single degraded FP32-subnormal float. Measured
 * (non-power-of-two mantissa on both operands so genuine multi-limb
 * precision is actually exercised -- a clean power-of-two operand is
 * already 1-limb-exact and hides this entirely): clean through worst-case
 * `t` exponent `-92`, first measurable drift at `-98` (already ~2.5 ULP),
 * climbing to ~590 ULP by `-107`. `bandIntermediateAdmits(minAbsExpArg -
 * maxAbsExpArg, margin)` reuses the same `kBandCarrierFloorExp`/`margin`
 * every other leg in this file does -- admitting through `-88`, eight
 * binades of measured slack before the `-96`/`-98` cliff.
 *
 * At `(maxAbsExpArg, minAbsExpArg) = (0, -107)`, `t`'s worst exponent is
 * `-107`, past this leg's `-88` edge, and measured aether `Band` error
 * there is ~590 ULP (@see the static_assert battery below, which replaces
 * a looser bound that covered only the divisor-ceiling concern:
 * `bandDivisorAdmits(0+1, -107)` alone is still correct as far as it
 * goes, and is kept as its own assert below, unchanged).
 */
[[nodiscard]] AETHER_DEVICEHOST() AETHER_FORCEINLINE() constexpr bool bandAtan2Admits(
    int maxAbsExpArg, int minAbsExpArg, int margin = kBandAdmissionMargin)
{
    return bandCeilingAdmits(maxAbsExpArg + 1, margin) && bandDivisorAdmits(maxAbsExpArg + 1, minAbsExpArg, margin)
        && bandIntermediateAdmits(maxAbsExpArg, margin) && bandIntermediateAdmits(minAbsExpArg - maxAbsExpArg, margin);
}

/// @brief The inverse-trig family's certified bound: half an ULP at 53
/// bits, ONE leg, NO absolute leg (@see `asin`'s own doc comment for the
/// derivation of why no absolute floor is needed).
inline constexpr int kBandInvTrigRelBoundExp = -53;

// =========================================================================
//  Two-sided static_asserts: one admitted case and one rejected case per
//  edge, so a bound that regresses fails to compile.
// =========================================================================
static_assert(bandAsinAdmits(kBandInvTrigMaxArgExp),
    "|x| == 1 must be ADMITTED -- asin(1) == pi/2 is one of this op's own "
    "exact points, and a margin under a mathematical domain would reject "
    "the domain's own endpoint");
static_assert(!bandAsinAdmits(kBandInvTrigMaxArgExp + 1),
    "one binade past the domain must be REJECTED -- there is no answer out "
    "there to be approximately right about");
static_assert(bandAsinAdmits(-1) && bandAsinAdmits(-1000),
    "every magnitude BELOW the domain is admissible without limit: asin "
    "has no floor leg, because near zero it returns its argument");

static_assert(bandAtan2Admits(0, 0) && bandAtan2Admits(20, -20),
    "atan2 on ordinary magnitudes, and on operands forty binades apart -- "
    "the RATIO is bounded by tan(5 deg) however far apart they are (this "
    "leg is unaffected by the output-floor correction below, which binds "
    "an ABSOLUTE spread, not a ratio)");
static_assert(!bandAtan2Admits(kBandNominalCeilingExp - kBandAdmissionMargin, 0),
    "the CEILING leg must bite one binade earlier than a bare op's, "
    "because atan2 forms a + b*tan(phi) above its larger operand");
static_assert(bandDivisorAdmits(0 + 1, -107) && !bandDivisorAdmits(0 + 1, -108),
    "the divisor-ceiling sub-claim (bandDivisorAdmits alone, independent of "
    "bandAtan2Admits's own tighter output-floor leg below) still holds at "
    "this edge: 2^-107 admitted, 2^-108 rejected (recip(den) reaches 2^108 "
    "there and 107 is all the ceiling grants)");
static_assert(bandAtan2Admits(-88, -88) && !bandAtan2Admits(-89, -89),
    "the third leg (@see bandAtan2Admits's own doc comment) must bite at "
    "the same edge every other op's intermediate-floor leg uses: "
    "kBandCarrierFloorExp + kBandAdmissionMargin = -88. Both operands tiny "
    "together (-89, past it) is exactly the measured failure: num/den's "
    "own lo/tail limbs underflow the FP32 hard subnormal floor before the "
    "division runs, 132 ULP off pi/4 at the -107/-107 case this leg rejects");
static_assert(!bandAtan2Admits(0, -107),
    "the fourth leg (the 'output floor' correction, @see bandAtan2Admits's "
    "own doc comment) rejects a case the divisor-ceiling sub-claim alone "
    "calls fine: at maxAbsExpArg=0, that sub-claim says -107 is admitted, "
    "but t's own worst-case exponent (minAbsExpArg - maxAbsExpArg = -107) "
    "is far past this carrier's measured cliff -- aether Band reads ~590 "
    "ULP off truth there. The quotient's relative conditioning (bounded) "
    "is not the same claim as its absolute precision (which fails past "
    "this edge) -- @see the doc comment's own citation of the measured "
    "sweep");
static_assert(bandAtan2Admits(0, -88) && !bandAtan2Admits(0, -89),
    "the FOURTH leg's own edge, reusing the SAME kBandCarrierFloorExp/"
    "margin every other leg in this file does: MEASURED clean through "
    "worst-case t exponent -92, first drift at -98 (~2.5 ULP) -- -88 is "
    "eight binades of slack before that cliff");

static_assert(kBandInvTrigRelBoundExp == -53,
    "the inverse family's certified bound is half an ULP at 53 bits with "
    "NO absolute leg -- if an absolute constant ever appears beside this "
    "one, this derivation has stopped being true");

} // namespace detail
} // namespace banded
} // namespace aether
