#!/usr/bin/env bash
# Copyright 2026 Alessandro Masat
# SPDX-License-Identifier: Apache-2.0
#
# tools/random/mint_golden.sh — mint (or verify) tests/random/golden_random.h.
#
# The golden header is the committed statement of WHAT aether::random's core
# stream is: `randomBits64`/`uniform01` exactly, `standardNormal` within a
# documented band, plus the keying chain. `tests/test_Random.cpp` checks the
# host arm against it and `tests/test_Random.cu` checks the DEVICE arm against
# the same rows, which is how aether's cross-mode bit-identity becomes a
# run rather than a claim.
#
# Usage:
#   tools/random/mint_golden.sh            # regenerate the header (deliberate act)
#   tools/random/mint_golden.sh --check    # verify the md5 fence only; no write
#
# HOST/CPP TREE ONLY — deliberately NOT wired into CMake. Minting is a
# deliberate, occasional act, not a build step: a header regenerated by the
# build would silently absorb whatever the stream happened to be that day,
# which is exactly the failure mode the golden exists to prevent.
#
# REFUSED UNDER $CI, for the same reason `tests/check_gate.sh --remint` is: a
# gate that regenerates its own expectation is a tautology.
#
# The row block in the header is md5-fenced. `--check` re-derives the digest of
# everything strictly between the BEGIN and END markers and compares it with
# the value recorded on the BEGIN line, so a hand-edit to one constant shows up
# without regenerating anything.
set -u -o pipefail

PROG="tools/random/mint_golden.sh"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

SRC="$REPO_ROOT/tools/random/mint_golden.cpp"
OUT="$REPO_ROOT/tests/random/golden_random.h"
BEGIN_RE='^\/\/ ---8<--- GOLDEN ROWS BEGIN'
END_RE='^\/\/ ---8<--- GOLDEN ROWS END'

MODE="mint"
if [ $# -gt 0 ]; then
    case "$1" in
        --check) MODE="check" ;;
        *) echo "$PROG: unknown argument '$1' (expected --check or nothing)" >&2; exit 2 ;;
    esac
fi

# Digest of the row block of $1 — everything STRICTLY between the two markers
# (the BEGIN line itself carries the digest, so it must not be part of it).
rows_md5() {
    sed -n "/$BEGIN_RE/,/$END_RE/p" "$1" | sed '1d;$d' | md5sum | cut -d' ' -f1
}

recorded_md5() {
    sed -n "/$BEGIN_RE/s/.*md5 = \([0-9a-f]\{32\}\).*/\1/p" "$1"
}

if [ "$MODE" = "check" ]; then
    [ -f "$OUT" ] || { echo "$PROG: no golden header at $OUT" >&2; exit 1; }
    HAVE="$(recorded_md5 "$OUT")"
    WANT="$(rows_md5 "$OUT")"
    if [ -z "$HAVE" ]; then
        echo "$PROG: RED — no md5 fence found on the BEGIN marker line of $OUT" >&2
        exit 1
    fi
    if [ "$HAVE" != "$WANT" ]; then
        echo "$PROG: RED — golden row block does not match its fence." >&2
        echo "         recorded=$HAVE  recomputed=$WANT" >&2
        exit 1
    fi
    echo "$PROG: fence OK — md5 $HAVE over the golden row block of tests/random/golden_random.h"
    exit 0
fi

if [ -n "${CI:-}" ]; then
    echo "$PROG: REFUSED — \$CI is set. A gate that regenerates its own expectation is a" >&2
    echo "         tautology; mint locally and commit the diff." >&2
    exit 1
fi

GXX="$(command -v g++ || true)"
[ -n "$GXX" ] || { echo "$PROG: g++ not found on PATH" >&2; exit 1; }
[ -f "$SRC" ] || { echo "$PROG: no minter source at $SRC" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Same optimisation/ISA flags the cpp test binary is built with, so the minted
# values are produced by the same code generation the tests will compare
# against. (The exact rows are contraction-invariant by construction — see
# aether/random/detail/Backend.h — but matching flags removes the question.)
echo "$PROG: compiling $SRC" >&2
"$GXX" -std=c++23 -O3 -march=x86-64-v3 -Wall -Wextra -DAETHER_CPP_MODE=1 \
    -I"$REPO_ROOT" -o "$TMP/mint_golden" "$SRC" || {
    echo "$PROG: RED — minter failed to compile" >&2
    exit 1
}

"$TMP/mint_golden" > "$TMP/golden_random.h" || {
    echo "$PROG: RED — minter failed at run time" >&2
    exit 1
}

MD5="$(rows_md5 "$TMP/golden_random.h")"
sed "s/@@GOLDEN_MD5@@/$MD5/" "$TMP/golden_random.h" > "$TMP/golden_random.final.h"

mkdir -p "$(dirname "$OUT")"
cp "$TMP/golden_random.final.h" "$OUT"

CORE="$(grep -c '^    { 0x' "$OUT")"
echo "$PROG: wrote $OUT — $CORE golden rows, fence md5 $MD5"
echo "$PROG: commit the diff in the SAME commit as whatever moved the stream."
